exp_params:
  LR: 0.0001
  batch_size: 32
  checkpoint: None
  data_path: /home/janier.soler/Databases/AUDIO/ASVspoof2019/MAT/PA
  dataset: asvspoofh
  ext: mat
  sliding_window: 64
  frames: 5
  img_size: 128
  scheduler_gamma: 0.95
  weight_decay: 1.0e-06
logging_params:
  manual_seed: 1265
  name: MobileNetV2LSTM_B
  save_dir: logs/PA/
model_params:
  in_channels: 3
  name: MobileNetV2LSTM_B
trainer_params:
  gpus: [0]
  max_epochs: 5
  max_nb_epochs: 5
