exp_params:
  LR: 0.0001
  batch_size: 32
  checkpoint: None
  data_path: /home/janier.soler/Databases/AUDIO/ASVspoof2019/MAT/LA
  dataset: asvspoof
  ext: mat
  sliding_window: 64
  frames: 5
  partition: CQT
  img_size: 128
  scheduler_gamma: 0.95
  weight_decay: 1.0e-06
logging_params:
  manual_seed: 1265
  name: DenseNetLSTM
  save_dir: logs/LA/CQT
model_params:
  in_channels: 3
  name: DenseNetLSTM
trainer_params:
  gpus: [1]
  max_epochs: 5
  max_nb_epochs: 5
